AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for EventBridge RuleGlue-to-EventBus-and-CloudWatch

Parameters:
  TargetAccountId:
    Type: String
    Description: Target AWS Account ID
    AllowedPattern: '^\d{12}$'
    ConstraintDescription: Must be a valid 12-digit AWS account ID

  TargetRegion:
    Type: String
    Description: Target AWS Region
    AllowedPattern: '^[a-z]{2}-[a-z]+-\d{1}$'
    ConstraintDescription: Must be a valid AWS region format (e.g., us-east-1)

  TargetEventBus:
    Type: String
    Default: "default"
    Description: Target AWS Event Bus Name

  LogRetentionInDays:
    Type: Number
    Default: 30
    Description: Number of days to retain logs in the CloudWatch Log Group.
  
Resources:
  EventBridgeLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/events/${AWS::StackName}'
      RetentionInDays: !Ref LogRetentionInDays
      Tags:
        - Key: Purpose
          Value: EventBridgeLogs
        - Key: Stack
          Value: !Ref AWS::StackName

  EventBridgeIAMrole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: PutEventsDestinationBus
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'events:PutEvents'
                Resource: !Sub "arn:aws:events:${TargetRegion}:${TargetAccountId}:event-bus/${TargetEventBus}"
        - PolicyName: PutLogsCloudWatch
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: !Sub "${EventBridgeLogGroup.Arn}:*"

  EventBridgeRule:
    Type: 'AWS::Events::Rule'
    DependsOn: 
      - EventBridgeIAMrole
      - EventBridgeLogGroup
    Properties:
      Name: !Sub "${AWS::StackName}-glue-changes"
      Description: Routes Glue Data Catalog Table State Changes Events to Target Region and Account for EventBus and to Target CloudWatch
      State: ENABLED
      EventBusName: default
      EventPattern:
        source:
          - "aws.glue"
        detail-type:
          - "Glue Data Catalog Database State Change"
          - "Glue Data Catalog Table State Change"
        detail:
          typeOfChange:
            - "CreateTable"
            - "DeleteTable"
            - "BatchDeleteTable"
            - "UpdateTable"
            - "CreatePartition"
            - "DeletePartition"
            - "BatchCreatePartition"
            - "BatchDeletePartition"
            - "UpdatePartition"
            - "BatchUpdatePartition"
      Targets:
        - Id: 'DestinationEventBus'
          Arn: !Sub "arn:aws:events:${TargetRegion}:${TargetAccountId}:event-bus/${TargetEventBus}"
          RoleArn: !GetAtt EventBridgeIAMrole.Arn
        - Id: 'EventBridgeLogs'
          Arn: !GetAtt EventBridgeLogGroup.Arn

Outputs:
  EventBridgeRuleName:
    Description: The name of the EventBridge rule.
    Value: !Ref EventBridgeRule

  EventBridgeLogGroupName:
    Description: The name of the CloudWatch Log Group.
    Value: !Ref EventBridgeLogGroup
