AWSTemplateFormatVersion: '2010-09-09'
Description: Glue Crawler Template for Fintech Data Quality Assurance Pipeline.

Parameters:
  ProjectName:
    Type: String
    Description: Name of the project

  SchemaDetectionBucketName:
    Type: String
    Description: The name for the scheme detection bucket.

  GlueDatabaseName:
    Type: String
    Description: The name for the Glue Data Catalog database.

  GlueCrawlerName:
    Type: String
    Description: Name for the Glue Crawler.

Resources:
  GlueCrawlerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-GlueCrawlerRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: GlueCrawlerS3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::${SchemaDetectionBucketName}/*'
                  - !Sub 'arn:aws:s3:::${SchemaDetectionBucketName}'
              - Effect: Allow
                Action:
                  - glue:CreateTable
                  - glue:UpdateTable
                  - glue:GetTable
                  - glue:GetTables
                  - glue:GetDatabase
                  - glue:CreateDatabase
                  - glue:GetDatabases
                  - glue:BatchCreatePartition
                  - glue:GetPartitions
                Resource:
                  - !Sub 'arn:aws:glue:${AWS::Region}:${AWS::AccountId}:catalog'
                  - !Sub 'arn:aws:glue:${AWS::Region}:${AWS::AccountId}:database/${GlueDatabaseName}'
                  - !Sub 'arn:aws:glue:${AWS::Region}:${AWS::AccountId}:table/${GlueDatabaseName}/*'

  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref "AWS::AccountId"
      DatabaseInput:
        Name: !Ref GlueDatabaseName

  GlueCrawler:
    Type: AWS::Glue::Crawler
    DependsOn: GlueDatabase 
    Properties:
      Name: !Ref GlueCrawlerName
      Role: !GetAtt GlueCrawlerRole.Arn
      DatabaseName: !Ref GlueDatabaseName
      Targets:
        S3Targets:
          - Path: !Sub 's3://${SchemaDetectionBucketName}/'
      SchemaChangePolicy:
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: DELETE_FROM_DATABASE

Outputs:
  GlueCrawlerName:
    Description: Name of the AWS Glue Crawler
    Value: !Ref GlueCrawler

  GlueDatabaseName:
    Description: Name of the Glue Data Catalog Database
    Value: !Ref GlueDatabase
