AWSTemplateFormatVersion: '2010-09-09'
Description: S3 Raw Data Bucket and S3 Data Quality Log Bucket for Fintech Data Quality Assurance Pipeline.

Parameters:
  ProjectName:
    Type: String
    Description: Name of the project

  SchemaDetectionBucketName:
    Type: String
    Description: The name for the schema detection bucket.

Resources:
  S3BucketSchemaDetection:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref SchemaDetectionBucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: ArchiveOrDeleteLogs
            Status: Enabled
            ExpirationInDays: 90
            Transitions:
              - TransitionInDays: 30
                StorageClass: GLACIER
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Name
          Value: !Ref SchemaDetectionBucketName
