AWSTemplateFormatVersion: '2010-09-09'
Description: IAM Role for AWS Lambda for the Fintech Data Quality Assurance Pipeline

Parameters:
  ProjectName:
    Type: String
    Default: DataQualityPipeline
    Description: Name of the project
  DataQualityLogsBucketArn:
    Type: String
    Description: ARN of the Data Quality Logs Bucket

Resources:
  IAMRoleLambda:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-LambdaRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: LambdaS3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: S3WriteAccess
                Effect: Allow
                Action:
                  - s3:PutObject
                Resource:
                  - !Sub '${DataQualityLogsBucketArn}/schema-changes/*'
                  - !Sub '${DataQualityLogsBucketArn}/validation-logs/*'
                  - !Sub '${DataQualityLogsBucketArn}/alerts/*'
              - Sid: S3ReadAccess
                Effect: Allow
                Action:
                  - s3:GetObject
                Resource:
                  - !Sub '${DataQualityLogsBucketArn}/schema-changes/*'
                  - !Sub '${DataQualityLogsBucketArn}/validation-logs/*'
                  - !Sub '${DataQualityLogsBucketArn}/alerts/*'
              - Sid: S3ListAccess
                Effect: Allow
                Action:
                  - s3:ListBucket
                Resource:
                  - !Ref DataQualityLogsBucketArn

Outputs:
  LambdaRoleARN:
    Value: !GetAtt IAMRoleLambda.Arn
    Export:
      Name: LambdaRoleARN
